name: Terrform Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true # For demo purposes, don't fail, just warn

      - name: Terraform Init
        working-directory: terraform/live/${{ matrix.environment }}
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/live/${{ matrix.environment }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform/live/${{ matrix.environment }}
        run: terraform apply -auto-approve

